kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
rules:
  - apiGroups: ['', 'apps', 'batch', 'extensions']
    resources:
      [
        'deployments',
        'services',
        'replicasets',
        'pods',
        'jobs',
        'cronjobs',
        'secrets',
        'roles',
      ]
    verbs: ['*']
