apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress-router
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
    # acme.cert-manager.io/http01-edit-in-place: 'true'
spec:
  tls:
    - hosts:
        - 'minesweepers.games'
      secretName: minesweeper-tls
  rules:
    - host: minesweepers.games
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - pathType: Prefix
            path: /web
            backend:
              service:
                name: webapp-color
                port:
                  number: 8080
    # - host: app-dev.minesweepers.games
    #   http:
    #     paths:
    #       - backend:
    #           serviceName: raz4app
    #           servicePort: 1338
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: echo-ingress-router
#   namespace: production
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     # certmanager.k8s.io/cluster-issuer: letsencrypt-prod
#     nginx.ingress.kubernetes.io/affinity: 'cookie'
#     nginx.ingress.kubernetes.io/session-cookie-name: 'route'
#     nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
#     nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
# spec:
#   # tls:
#   #   - hosts:
#   #       - 'raz4api.minesweepers.games'
#   #       - 'app.minesweepers.games'
#   #     secretName: letsencrypt-prod
#   rules:
#     # - host: raz4api.minesweepers.games
#     - http:
#         paths:
#           - pathType: Prefix
#             path: '/production'
#             backend:
#               service:
#                 name: frontend
#                 port:
#                   number: 80
# - host: app.minesweepers.games
#   http:
#     paths:
#       - backend:
#           serviceName: raz4app
#           servicePort: 1338
# - host: beta.minesweepers.games
#   http:
#     paths:
#       - backend:
#           serviceName: raz4app
#           servicePort: 1338
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: kube-prometheus-stack
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # acme.cert-manager.io/http01-edit-in-place: 'true'
spec:
  tls:
    - hosts:
        - 'monitoring.minesweepers.games'
      secretName: monitoring-tls
  rules:
    - host: monitoring.minesweepers.games
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: kube-prometheus-stack-grafana
                port:
                  number: 80
